import type { RoastReport } from './types';

export function formatMarkdownReport(report: RoastReport): string {
  const lines: string[] = [];

  lines.push(`# 🔥 Codebase Roast: \`${report.repoName}\``);
  lines.push('');
  lines.push(`> *Generated by **codebase-roast** · Powered by Claude AI*`);
  lines.push('');
  lines.push('---');
  lines.push('');

  // Score section
  lines.push('## 📊 Roast Score');
  lines.push('');
  lines.push(`### ${report.roastScore} / 10`);
  lines.push('');
  lines.push(renderScoreBar(report.roastScore));
  lines.push('');
  lines.push(`*${getScoreLabel(report.roastScore)}*`);
  lines.push('');
  lines.push('---');
  lines.push('');

  // Summary roast
  lines.push('## 🎤 The Verdict');
  lines.push('');
  lines.push(report.summary);
  lines.push('');
  lines.push('---');
  lines.push('');

  // Specific callouts
  lines.push('## 🔍 Specific Callouts');
  lines.push('');

  for (let i = 0; i < report.callouts.length; i++) {
    const c = report.callouts[i];
    lines.push(`### ${i + 1}. ${c.title}`);
    lines.push('');
    lines.push(c.description);

    if (c.file) {
      lines.push('');
      lines.push(`**File:** \`${c.file}\``);
    }

    if (c.snippet) {
      lines.push('');
      lines.push('```');
      lines.push(c.snippet.trim());
      lines.push('```');
    }

    lines.push('');
  }

  lines.push('---');
  lines.push('');
  lines.push('## ⚖️ Final Sentence');
  lines.push('');
  lines.push(`> ${report.verdict}`);
  lines.push('');
  lines.push('---');
  lines.push('');
  lines.push('*Roasted with ❤️ by [codebase-roast](https://www.npmjs.com/package/codebase-roast)*');

  return lines.join('\n');
}

export function printTerminalReport(report: RoastReport): void {
  const divider = '─'.repeat(60);
  const bold = (s: string) => `\x1b[1m${s}\x1b[0m`;
  const dim = (s: string) => `\x1b[2m${s}\x1b[0m`;
  const cyan = (s: string) => `\x1b[36m${s}\x1b[0m`;
  const yellow = (s: string) => `\x1b[33m${s}\x1b[0m`;
  const red = (s: string) => `\x1b[31m${s}\x1b[0m`;
  const green = (s: string) => `\x1b[32m${s}\x1b[0m`;

  const scoreColor = report.roastScore >= 7 ? green
    : report.roastScore >= 4 ? yellow
    : red;

  console.log('');
  console.log(bold(`🔥  CODEBASE ROAST: ${report.repoName}`));
  console.log(divider);
  console.log('');
  console.log(bold('ROAST SCORE'));
  console.log(`  ${scoreColor(bold(`${report.roastScore}/10`))}  ${renderScoreBar(report.roastScore)}`);
  console.log(`  ${dim(getScoreLabel(report.roastScore))}`);
  console.log('');
  console.log(divider);
  console.log('');
  console.log(bold('THE ROAST'));
  console.log('');
  console.log(wrapText(report.summary, 58, '  '));
  console.log('');
  console.log(divider);
  console.log('');
  console.log(bold('SPECIFIC CALLOUTS'));
  console.log('');

  for (let i = 0; i < report.callouts.length; i++) {
    const c = report.callouts[i];
    console.log(`  ${cyan(bold(`${i + 1}. ${c.title}`))}`);
    if (c.file) console.log(`     ${dim(`📁 ${c.file}`)}`);
    console.log('');
    console.log(wrapText(c.description, 54, '     '));
    if (c.snippet) {
      console.log('');
      console.log(dim('     ' + c.snippet.trim().split('\n').slice(0, 3).join('\n     ')));
    }
    console.log('');
  }

  console.log(divider);
  console.log('');
  console.log(bold('FINAL VERDICT'));
  console.log('');
  console.log(`  ${yellow(`"${report.verdict}"`)}`);
  console.log('');
  console.log(divider);
}

function renderScoreBar(score: number): string {
  const filled = '█'.repeat(score);
  const empty = '░'.repeat(10 - score);
  return `${filled}${empty}`;
}

function getScoreLabel(score: number): string {
  if (score >= 9) return 'Peak engineering. Your rubber duck is proud.';
  if (score >= 7) return 'Pretty solid. A few rough edges, but nothing therapy cannot fix.';
  if (score >= 5) return 'It works… technically. Stockholm syndrome may be required.';
  if (score >= 3) return 'More red flags than a Formula 1 race. Please seek help.';
  return 'A digital dumpster fire. Beautiful in its own chaotic way.';
}

function wrapText(text: string, width: number, indent: string): string {
  const words = text.split(' ');
  const lines: string[] = [];
  let current = indent;

  for (const word of words) {
    if (current.length + word.length + 1 > width + indent.length) {
      lines.push(current);
      current = indent + word;
    } else {
      current += (current === indent ? '' : ' ') + word;
    }
  }
  if (current !== indent) lines.push(current);
  return lines.join('\n');
}
